name: Discord notify
on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post all commits (plus merge) in order
        env:
          WEBHOOK:        ${{ secrets.DISCORD_NOTIFY }}
          REPO:           ${{ github.repository }}
          BRANCH:         ${{ github.ref_name }}
          COMMITS_JSON:   ${{ toJson(github.event.commits) }}
          HEAD_JSON:      ${{ toJson(github.event.head_commit) }}
          ACTOR_FALLBACK: ${{ github.actor }}
        shell: bash
        run: |
          set -euo pipefail

          repo_short="${REPO#*/}"

          combined="$(
            jq -cs '
              (.[0] // []) as $c | (.[1] // null) as $h |
              ($c + (if $h==null then [] else [$h] end))
              | map(select(.id?)) | unique_by(.id) | sort_by(.timestamp // "")
            ' <(printf '%s' "${COMMITS_JSON:-[]}") <(printf '%s' "${HEAD_JSON:-null}")
          )"

          jq -c '.[] | {id, url, message, timestamp, author}' <<< "$combined" | while read -r c; do
            id="$(jq -r '.id // empty' <<< "$c")"
            url="$(jq -r '.url // empty' <<< "$c")"
            [ -z "$url" ] && url="https://github.com/$REPO/commit/$id"
            short="${id:0:7}"
            msg="$(jq -r '.message // ""' <<< "$c")"
            ts="$(jq -r '.timestamp // empty' <<< "$c")"
            login="$(jq -r '.author.username // empty' <<< "$c")"
            [ -z "$login" ] && login="$ACTOR_FALLBACK"
            [ -z "$ts" ] && ts="$(date -Iseconds)"
            iso="$(date -u -d "$ts" +'%Y-%m-%dT%H:%M:%SZ')"

            jq -n \
              --arg login "$(jq -r --arg fb "$ACTOR_FALLBACK" '(.author.username // "") | if length==0 then $fb else . end' <<< "$c")" \
              --arg short "$short" \
              --arg url   "$url" \
              --arg msg   "$msg" \
              --arg title "${repo_short} - ${BRANCH}" \
              --arg link  "https://github.com/${REPO}/tree/${BRANCH}" \
              --arg iso   "$(date -u -d "${ts:-$(date -Iseconds)}" +'%Y-%m-%dT%H:%M:%SZ')" \
              '{
                username: "GitHub",
                avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                embeds: [{
                  title: $title,
                  url:   $link,
                  color: 3113463,
                  author: {
                    name: $login,
                    url: ("https://github.com/" + $login),
                    icon_url: ("https://avatars.githubusercontent.com/" + $login)
                  },
                  description: ("[`" + $short + "`](" + $url + ")\n" + $msg),
                  footer: { text: ("[`" + $short + "`] • " + $title) },
                  timestamp: $iso
                }]
              }' \
            | curl -fsS -H 'Content-Type: application/json' -d @- "$WEBHOOK" >/dev/null
          done
