name: Discord notify
on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post all commits (plus merge) in order
        env:
          WEBHOOK:        ${{ secrets.DISCORD_NOTIFY }}
          REPO:           ${{ github.repository }}
          BRANCH:         ${{ github.ref_name }}
          COMMITS_JSON:   ${{ toJson(github.event.commits) }}
          HEAD_JSON:      ${{ toJson(github.event.head_commit) }}
          ACTOR_FALLBACK: ${{ github.actor }}
        shell: bash
        run: |
          set -euo pipefail

          echo "${COMMITS_JSON:-[]}"  > commits.json
          echo "${HEAD_JSON:-null}"   > head.json

          jq -cs '
            (.[0] // []) as $c |
            (.[1] // null) as $h |
            ($c + (if $h==null then [] else [$h] end))
            | map(select(.id?))
            | unique_by(.id)
            | sort_by(.timestamp // "")
          ' commits.json head.json > list.json

          repo_short="$(awk -F/ '{print ($2?$2:$0)}' <<< "$REPO")"

          jq -c '.[] | {id, url, message, timestamp, author}' list.json | while read -r c; do
            id="$(jq -r '.id // empty' <<< "$c")"
            url="$(jq -r '.url // empty' <<< "$c")"
            msg="$(jq -r '.message // ""' <<< "$c")"
            ts="$(jq -r '.timestamp // empty' <<< "$c")"
            login="$(jq -r '.author.username // empty' <<< "$c")"
            [ -z "$login" ] && login="$ACTOR_FALLBACK"

            [ -z "$url" ] && [ -n "$id" ] && url="https://github.com/$REPO/commit/$id"
            short="${id:0:7}"
            desc="[$short]($url)\n$msg"

            if [ -z "$ts" ] || ! date -d "$ts" >/dev/null 2>&1; then ts="$(date -Iseconds)"; fi
            iso_utc="$(date -u -d "$ts" +"%Y-%m-%dT%H:%M:%SZ")"

            jq -n \
              --arg login "$login" \
              --arg desc "$desc" \
              --arg foot "$repo_short - $BRANCH" \
              --arg iso "$iso_utc" \
              '{
                username: "GitHub",
                avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                embeds: [{
                  color: 3113463,
                  author: {
                    name: $login,
                    url: ("https://github.com/" + $login),
                    icon_url: ("https://avatars.githubusercontent.com/" + $login)
                  },
                  description: $desc,
                  footer: { text: $foot },
                  timestamp: $iso
                }]
              }' \
            | curl -fsS -H 'Content-Type: application/json' -d @- "$WEBHOOK" >/dev/null
          done
