name: Discord head-commit

on:
  push:

jobs:
  notify:
    runs-on: windows-latest
    steps:
      - name: Post head commit only (handles merges)
        shell: pwsh
        env:
          API_URL:     ${{ secrets.DISCORD_NOTIFY }}
          REPO:        ${{ github.repository }}
          BRANCH:      ${{ github.ref_name }}
          # Prefer the username from the head commit; fallback to actor (works for merges)
          ACTOR_LOGIN: ${{ github.event.head_commit.author.username || github.actor }}
          MSG:         ${{ toJSON(github.event.head_commit.message) }}
          TS:          ${{ github.event.head_commit.timestamp }}
        run: |
          if (-not $env:TS) { exit 0 }  # no head_commit (e.g., tag/branch delete)
          $payload = @{
            repo      = $env:REPO
            branch    = $env:BRANCH
            actor     = $env:ACTOR_LOGIN
            message   = $env:MSG
            timestamp = $env:TS
          } | ConvertTo-Json -Depth 5
          Invoke-RestMethod -Uri $env:API_URL -Method Post -ContentType 'application/json' -Body $payload | Out-Null
