name: Discord head-commit

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post head commit only
        env:
          API_URL: ${{ secrets.DISCORD_NOTIFY }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          ACTOR_LOGIN: ${{ github.event.head_commit.author.username || github.actor }}
          ACTOR_NAME: ${{ github.event.head_commit.author.name }}
          MSG: ${{ toJSON(github.event.head_commit.message) }}
          TS: ${{ github.event.head_commit.timestamp }}
        shell: bash
        run: |
          actor="$ACTOR_LOGIN"
          if [ -z "$actor" ] || [ "$actor" = "null" ]; then actor="$ACTOR_NAME"; fi
          jq -n \
            --arg repo "$REPO" \
            --arg branch "$BRANCH" \
            --arg actor "$actor" \
            --arg message "$MSG" \
            --arg timestamp "$TS" \
            '{repo:$repo, branch:$branch, actor:$actor, message:$message, timestamp:$timestamp}' \
          | curl -sS -X POST "$API_URL" -H 'Content-Type: application/json' -d @-
